pathogenDB/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
	url(r'^accounts/login', 'django.contrib.auth.views.login', {'template_name': 'pathogenDB/login.html'}, name='login'),
	url(r'^accounts/logout', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    url(r'^$', views.index),
	url(r'^pathogenSite/', include('pathogenSite.urls')),
	#url(r'^taxon-group/', include('ssuProkSite.urls')),
]

pathogenSite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from pathogenSite import views
from pathogenSite.views.analysis import PathogenAnalysis
from pathogenSite.views.report import ReportTest


urlpatterns = [
	url(r'^$', login_required(views.PathogenEditView.as_view()),
		name='ezbio-intro'),
	url(r'^pathogen$', login_required(views.PathogenList.as_view()), 
		name='pathogen'),
	url(r'^pathogen/(?P<slug>\d+)$', 
		login_required(views.PathogenUpdateView.as_view()),
		name='pathogen_update'),
	url(r'^sample$', 
		login_required(views.SampleListView.as_view()),
		#views.SampleListView.as_view(),
		name='sample'),
	url(r'^sample-upload$',
		login_required(views.CLCSampleUploadFormView.as_view()), 
		name='sample-upload'),
	url(r'^sample-analysis$',
		login_required(PathogenAnalysis.as_view()), 
		name='sample-analysis'),
	url(r'^report$',
		#login_required(ReportTest.as_view()), 
		ReportTest.as_view(), 
		name='report'),
	url(r'^test$', views.TestView.as_view(), name='test'),
]

pathogenSite/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin sqlcustom [app_label]'
# into your database.
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User as Auth_user
from time import strftime


def user_directory_path(instance, filename):
	return 'user_{0}/{2}/{1}'.format(instance.owner.id, filename, 
			strftime('%Y%m%d%H%M%S'))

"""
class CLCSampleFile(models.Model):
	name = models.CharField(unique=False, max_length=250)
	upload_date = models.DateTimeField(auto_now_add=True)
	clc_file = models.FileField(upload_to=user_directory_path)
"""

class CLCSample(models.Model):
	name = models.CharField(unique=False, max_length=250)
	owner = models.ForeignKey(Auth_user)
	upload_date = models.DateTimeField(auto_now_add=True)
	clc_file = models.FileField(upload_to=user_directory_path)


class Nomen(models.Model):
	PATHOGEN = (
			(0, 'NA'),
			(1, 'Not pathogen'),
			(2, 'Not known'),
			(3, 'Pathogen'),
			(4, 'Opportunistic pathogen'),
	)
	uid = models.AutoField(primary_key=True)
	name = models.CharField(unique=True, max_length=250)
	name_kor = models.CharField(max_length=250, blank=True, null=True)
	rank = models.IntegerField()
	status = models.IntegerField()
	authors = models.CharField(max_length=250, blank=True, null=True)
	type_taxon = models.CharField(max_length=250, blank=True, null=True)
	is_type = models.IntegerField()
	basonym = models.TextField(blank=True, null=True)
	taxonomy = models.TextField(blank=True, null=True)
	stamp_insert = models.DateTimeField()
	stamp_update = models.DateTimeField()
	created_by = models.CharField(max_length=100)
	updated_by = models.CharField(max_length=100, blank=True, null=True)
	ncbi_taxid = models.IntegerField()
	reference = models.CharField(max_length=250, blank=True, null=True)
	vlist = models.IntegerField(blank=True, null=True)
	wiki_kor = models.TextField(blank=True, null=True)
	wiki_kor_created_by = models.CharField(max_length=50, blank=True, null=True)
	wiki_kor_updated_by = models.CharField(max_length=50, blank=True, null=True)
	wiki_eng = models.TextField(blank=True, null=True)
	wiki_eng_created_by = models.CharField(max_length=50, blank=True, null=True)
	wiki_eng_updated_by = models.CharField(max_length=50, blank=True, null=True)
	wiki_ref = models.TextField(blank=True, null=True)
	pathogen_human = models.IntegerField(default=0, choices=PATHOGEN)
	pathogen_animal = models.IntegerField(default=0, choices=PATHOGEN)
	pathogen_plant = models.IntegerField(default=0, choices=PATHOGEN)
	pathogen_classification = models.IntegerField()
	pathogen_supervision = models.IntegerField()
	pathogen_eng = models.TextField(blank=True, null=True)
	pathogen_kor = models.TextField(blank=True, null=True)
	pathogen_disease_kor = models.TextField(blank=True, null=True)
	pathogen_disease_eng = models.TextField(blank=True, null=True)
	pathogen_route_kor = models.TextField(blank=True, null=True)
	pathogen_route_eng = models.TextField(blank=True, null=True)
	pathogen_symptom_kor = models.TextField(blank=True, null=True)
	pathogen_symptom_eng = models.TextField(blank=True, null=True)
	pathogen_prognosis_kor = models.TextField(blank=True, null=True)
	pathogen_prognosis_eng = models.TextField(blank=True, null=True)
	pathogen_treatment_kor = models.TextField(blank=True, null=True)
	pathogen_treatment_eng = models.TextField(blank=True, null=True)
	other_information_kor = models.TextField(blank=True, null=True)
	other_information_eng = models.TextField(blank=True, null=True)
	source_kor = models.TextField(blank=True, null=True)
	source_eng = models.TextField(blank=True, null=True)
	gc_ratio = models.CharField(max_length=50, blank=True, null=True)
	cell_size = models.CharField(max_length=50, blank=True, null=True)
	growth_temp = models.CharField(max_length=100, blank=True, null=True)
	gram_stain = models.IntegerField()
	morphology = models.TextField(blank=True, null=True)
	comment = models.TextField(blank=True, null=True)
	pathogen_link = models.TextField(blank=True, null=True)
	genome_strain_count = models.IntegerField()
	genome_size_mean = models.IntegerField()
	genome_acc_type_strain = models.CharField(max_length=50, blank=True, null=True)
	genome_size_type_strain = models.IntegerField(blank=True, null=True)
	genome_size_median = models.IntegerField()
	genome_size_sd = models.IntegerField()
	genome_size_min = models.IntegerField()
	genome_size_max = models.IntegerField()
	genome_gc_type_strain = models.FloatField()
	genome_gc_mean = models.FloatField()
	genome_gc_median = models.FloatField()
	genome_gc_sd = models.FloatField()
	genome_gc_min = models.FloatField()
	genome_gc_max = models.FloatField()
	check_edit_list = models.CharField(max_length=50)
	check_add_list = models.CharField(max_length=50)

	class Meta:
		managed = False
		db_table = 'nomen'


class NomenCopy(models.Model):
    uid = models.AutoField(primary_key=True)
    name = models.CharField(unique=True, max_length=250)
    name_kor = models.CharField(max_length=250, blank=True, null=True)
    rank = models.IntegerField()
    status = models.IntegerField()
    authors = models.CharField(max_length=250, blank=True, null=True)
    type_taxon = models.CharField(max_length=250, blank=True, null=True)
    is_type = models.IntegerField()
    basonym = models.TextField(blank=True, null=True)
    taxonomy = models.TextField(blank=True, null=True)
    stamp_insert = models.DateTimeField()
    stamp_update = models.DateTimeField()
    created_by = models.CharField(max_length=100)
    updated_by = models.CharField(max_length=100, blank=True, null=True)
    ncbi_taxid = models.IntegerField()
    reference = models.CharField(max_length=250, blank=True, null=True)
    vlist = models.IntegerField(blank=True, null=True)
    wiki_kor = models.TextField(blank=True, null=True)
    wiki_kor_created_by = models.CharField(max_length=50, blank=True, null=True)
    wiki_kor_updated_by = models.CharField(max_length=50, blank=True, null=True)
    wiki_eng = models.TextField(blank=True, null=True)
    wiki_eng_created_by = models.CharField(max_length=50, blank=True, null=True)
    wiki_eng_updated_by = models.CharField(max_length=50, blank=True, null=True)
    wiki_ref = models.TextField(blank=True, null=True)
    pathogen_human = models.IntegerField()
    pathogen_animal = models.IntegerField()
    pathogen_plant = models.IntegerField()
    pathogen_classification = models.IntegerField()
    pathogen_eng = models.TextField(blank=True, null=True)
    pathogen_kor = models.TextField(blank=True, null=True)
    pathogen_disease_kor = models.TextField(blank=True, null=True)
    pathogen_disease_eng = models.TextField(blank=True, null=True)
    pathogen_route_kor = models.TextField(blank=True, null=True)
    pathogen_route_eng = models.TextField(blank=True, null=True)
    pathogen_symptom_kor = models.TextField(blank=True, null=True)
    pathogen_symptom_eng = models.TextField(blank=True, null=True)
    pathogen_prognosis_kor = models.TextField(blank=True, null=True)
    pathogen_prognosis_eng = models.TextField(blank=True, null=True)
    pathogen_treatment_kor = models.TextField(blank=True, null=True)
    pathogen_treatment_eng = models.TextField(blank=True, null=True)
    other_information_kor = models.TextField(blank=True, null=True)
    other_information_eng = models.TextField(blank=True, null=True)
    source_kor = models.TextField(blank=True, null=True)
    source_eng = models.TextField(blank=True, null=True)
    gc_ratio = models.CharField(max_length=50, blank=True, null=True)
    cell_size = models.CharField(max_length=50, blank=True, null=True)
    growth_temp = models.CharField(max_length=100, blank=True, null=True)
    gram_stain = models.IntegerField()
    morphology = models.TextField(blank=True, null=True)
    comment = models.TextField(blank=True, null=True)
    pathogen_link = models.TextField(blank=True, null=True)
    genome_strain_count = models.IntegerField()
    genome_size_mean = models.IntegerField()
    genome_size_median = models.IntegerField()
    genome_size_sd = models.IntegerField()
    genome_size_min = models.IntegerField()
    genome_size_max = models.IntegerField()
    genome_gc_mean = models.FloatField()
    genome_gc_median = models.FloatField()
    genome_gc_sd = models.FloatField()
    genome_gc_min = models.FloatField()
    genome_gc_max = models.FloatField()
    check_edit_list = models.CharField(max_length=50)
    check_add_list = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'nomen_copy'


class NomenFile(models.Model):
    uid = models.AutoField(primary_key=True)
    f_parent_uid = models.IntegerField()
    f_attachment = models.CharField(max_length=200)
    f_file_name = models.CharField(max_length=200)
    f_link = models.CharField(max_length=300)
    f_comment = models.CharField(max_length=500)
    f_type = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'nomen_file'


class PathogenDisease(models.Model):
    uid = models.AutoField(primary_key=True)
    name = models.CharField(unique=True, max_length=250)
    name_kor = models.CharField(max_length=250)
    rank = models.IntegerField()
    status = models.IntegerField()
    authors = models.CharField(max_length=250)
    type_taxon = models.CharField(max_length=250)
    is_type = models.IntegerField()
    basonym = models.TextField()
    stamp_insert = models.DateTimeField()
    stamp_update = models.DateTimeField()
    created_by = models.CharField(max_length=100)
    updated_by = models.CharField(max_length=100)

pathogenSite/views/analysis.py
import json

from django import forms
from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView, ListView, FormView

from pathogenSite.models import Nomen, CLCSample

from CheckPathogen import Reporter


class PathogenAnalysis(TemplateView):
	template_name = 'pathogenSite/report/new_report.html'
	#template_name = 'pathogenSite/report/report.html'

	def post(self, request, *args, **kwargs):
		"""
		total_micro_dist = {
		'sample1': [{'sample':, 'genus':, 'species':, 'count':, 'is_pathogen':,
			'pathogen_human':, 'pathogen_animal':, 'pathogen_plant':}],
		}
		"""
		context = self.get_context_data()
		clc_files = request.POST.getlist('sample')

		total_micro_dist = {}
		samples = []
		for clc_file in clc_files:
			clc_file = json.loads(clc_file)
			file_path = clc_file['path']
			sample_name = clc_file['name']
			samples.append(sample_name)

			reporter = Reporter(file_path)
			reporter.check_rank_count()
			micro_dist = reporter.get_micro_dist(end_rank='phylum')
			total_micro_dist[sample_name] = []
			for comp in micro_dist:
				comp['sample'] = sample_name
				total_micro_dist[sample_name].append(comp)
			
	
		# Read Count Assignment Flow
		# Possible Pathogens & Diseases
		# Total Microbiome Distribution 
		# Pathogen Distribution
		# Pathogen Information
		context['samples'] = samples
		context['data'] = json.dumps(total_micro_dist)
		return super(PathogenAnalysis, self).render_to_response(context)

	def get_context_data(self, **kwargs): # this will be called 'GET' request
		context = super(PathogenAnalysis, self).get_context_data(**kwargs)
		return context

pathogenSite/templates/pathogenSite/analysis.html
{% extends "pathogenSite/base.html" %}

{% block title %}Introduction Page{% endblock %}

{% block content %}
<div>good{{well}}</div>
{% endblock %}

pathogenSite/templates/pathogenSite/base.html
{% load i18n staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
	<!--<link rel="icon" href="../../favicon.ico">-->

	<title>{% block title %} First Page {% endblock %}</title>

	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css'%}">
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.min.css'%}">
	<link rel="stylesheet" href="{% static 'jquery-ui-1.11.4/jquery-ui.min.css'%}">

	<!-- jquery, bootstrap, jquery-ui, d3, crossfilter, dc -->
	<script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
	<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'jquery-ui-1.11.4/jquery-ui.min.js'%}"></script>


	<!-- Custom styles for this template -->
	<link rel="stylesheet" href="{%static 'pathogenSite/css/dashboard.css'%}">

  {% block style %}{% endblock %}	  
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
					<a class="navbar-brand" href="{% url 'ezbio-intro' %}">Pathogen DB</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="#">{{ request.user }}</a></li>
						<li><a href="{% url 'logout' %}">logout</a></li>
            <li><a href="#">Help</a></li>
					</ul>
					<!--
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
					</form>
					-->
        </div>
      </div>
    </nav>

    <div class="container-fluid">
	  <div class="row">
      <div class="col-sm-3 col-md-2 sidebar">
        <ul class="nav nav-sidebar">
		  <li class="pathogen_list"><a href="{% url 'pathogen' %}">Pathogen List</a></li>
		  <li class="sample_list"><a href="{% url 'sample' %}">Sample List</a></li>
		  <li class="sample_upload"><a href="{% url 'sample-upload' %}">Sample Upload</a></li>
		  <!--
		  <li class="report_test"><a href="{% url 'report' %}">Report Test</a></li>
		  <li class="dc_test"><a href="{% url 'test' %}">DC Test</a></li>
		  -->
        </ul>
      </div>
		<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        {% block content %}
          <h1 class="page-header">Dashboard</h1>

          <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/sky" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/sky" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
          </div>

	    {% endblock %}
        {% block pagination %}
        {% if is_paginated %}
        <div class="pagination">
          <span class="page-links">
            {% if page_obj.has_previous %}
						<a href="?{{ prev_url }}&page={{ page_obj.previous_page_number }}">
              previous
            </a>
            {% endif %}
            <span class="page-current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>
            {% if page_obj.has_next %}
						<a href="?{{ prev_url }}&page={{ page_obj.next_page_number }}">
							next
						</a>
            {% endif %}
          </span>
        </div>
        {% endif %}
        {% endblock %}
        </div>
      </div>
	</div>

	<script>
		$(document).ready(function(){
			var clickedNav = '.{{ clicked_nav }}';
			$(clickedNav).addClass('active');
		});
	</script>
		{% block script %}{% endblock %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
	<!--
    <script src="../../assets/js/vendor/holder.js"></script>
	-->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
	<!--
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
	-->
  </body>
</html>

pathogenSite/templates/pathogenSite/intro.html
{% extends "pathogenSite/base.html" %}

{% block title %}Introduction Page{% endblock %}
{% block content %}
Pathogen Test Page
{% endblock %}

pathogenSite/templates/pathogenSite/pathogen_detail.html
{% extends "pathogenSite/base.html" %}

{% block title %}Introduction Page{% endblock %}
{% block content %}
{{ object.uid }}, {{ object.name }}, {{ object.human }}
{% endblock %}

pathogenSite/templates/pathogenSite/pathogen_edit_form.html
<div class="row">
	<form id="pathogen_update_form" method='post' class="form-horizontal" role="form" action='{% url 'pathogen_update' object.uid %}'>
		<div class=form-group>
			<button type="submit" class="btn btn-submit col-md-offset-2">Submit</button>
		</div>
    {% csrf_token %}
		<!--	
		{{ form }}
		-->
		{{ form.non_field_errors }}
		{% for field in form %}
		<div class="form-group">
			{% if field.errors %}
			<ul class="form-errors">
				{% for error in field.errors %}
				<li>
					<span class="fa fa-exclamation-triangle"></span> 
					<strong>{{ error|escape }}</strong>
				</li>
				{% endfor %}
			</ul>
			{% endif %}
			<label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
			<div class="col-sm-10">
				{{ field }} 
			</div>
			{% if field.help_text %}
			<div class="form-helptext">{{ field.help_text }}</div>
			{% endif %} 
		</div>
		{% endfor %}
  </form>
</div>

pathogenSite/templates/pathogenSite/pathogen_list.html
{% extends "pathogenSite/base.html" %}

{% block title %}Introduction Page{% endblock %}

{% block style %}
<style>
	.row{
		margin-top: 5px;
	}
</style>
{% endblock %}

{% block content %}
<div id="myModal2" class="modal fade">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-body" style="text-align: center;">
				<span class="glyphicon glyphicon-ok-sign">&nbsp;successfully updated</span>

			</div>
		</div>
	</div>
</div>

<div id="form-modal" class="modal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
aria-hidden="true">&times;</button>
				<h4 class="modal-title">Edit Information</h4>
			</div>
			<div id="form-modal-body" class="modal-body">
				<p>One fine body&hellip;</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismi
ss="modal">Close</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="row">
	<form>
		{% csrf_token %}
		
		<div class="col-sm-6">
			<div class="row">
				<div class="form-group">
					{{ form.pathogen_human.errors }}
					<label for="{{ form.pathogen_human.id_for_label }}" class="col-sm-3 control-label">Human Pathogen</label>
					<div class="col-sm-7">
						{{ form.pathogen_human }}	
					</div>                  
				</div>
			</div>

			<div class="row">
				<div class="form-group">
					{{ form.pathogen_animal.errors }}
					<label for="{{ form.pathogen_animal.id_for_label }}" class="col-sm-3 control-label">animal Pathogen</label>
					<div class="col-sm-7">
						{{ form.pathogen_animal }}	
					</div>                  
				</div>
			</div>

			<div class="row">
				<div class="form-group">
					{{ form.pathogen_plant.errors }}
					<label for="{{ form.pathogen_plant.id_for_label }}" class="col-sm-3 control-label">plant Pathogen</label>
					<div class="col-sm-7">
						{{ form.pathogen_plant }}	
					</div>                  
				</div>
			</div>
		</div>

		<div class="col-sm-6">
			<div class="row">
				<div class="form-group">
					{{ form.name.errors }}
					<label for="{{ form.name.id_for_label }}" class="col-sm-3 control-label">Name</label>
					<div class="col-sm-9">
						<input type="{{ form.name.field.widget.input_type }}" class="form-control" id="{{ form.name.id_for_label }}" name="{{ form.name.name }}" placeholder="{{ form.name.name }}">
					</div>                  
				</div>
			</div>
			
			<div class="row">
				<div class="form-group">
					{{ form.pathogen_disease_eng.errors }}
					<label for="{{ form.pathogen_disease_eng.id_for_label }}" class="col-sm-3 control-label">Disease</label>
					<div class="col-sm-9">
						<input type="{{ form.pathogen_disease_eng.field.widget.input_type }}" class="form-control" id="{{ form.pathogen_disease_eng.id_for_label }}" name="{{ form.pathogen_disease_eng.name }}" placeholder="{{ form.pathogen_disease_eng.name }}">
					</div>                  
				</div>
			</div>

			<div class="row text-right">
				<button type="submit" class="btn btn-info">Search</button>
				&nbsp;&nbsp;&nbsp; 
			</div>
		</div>

	</form>
</div>
<hr/>
<div class="table-responsive">
	<table class="table table-striped table-hover">
		<col width="8%">
		<col width="18%">
		<col width="10%">
		<col width="10%">
		<col width="10%">
		<col width="">
		<thead>
			<tr>
				<th class="resize">ID</th>
				<th>Name</th>
				<th>Pathogen Human</th>
				<th>Pathogen Animal</th>
				<th>Pathogen Plant</th>
				<th>Disease</th>
			</tr>
		</thead>
		<tbody>
			{% for pathogen in pathogen_list %}
			<tr>
				<td class="uid">
					<a id="edit_pathogen" class="fa fa-pencil" data-toggle="modal" href="{% url 'pathogen_update' pathogen.uid %}" data-target="#modal" title="edit item" data-tooltip>
						{{ pathogen.uid }}
					</a>
					<!--
					<a href = "{% url 'pathogen_update' pathogen.uid %}">
						{{ pathogen.uid }}
					</a>
					-->
				</td>
				<td>{{ pathogen.name }}</td>
				<td>{{ pathogen.get_pathogen_human_display }}</td>
				<td>{{ pathogen.get_pathogen_animal_display }}</td>
				<td>{{ pathogen.get_pathogen_plant_display }}</td>
				<td>{{ pathogen.pathogen_disease_eng }}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% endblock %}
{% block script %}
<script>
$(document).ready(function () {
	$('select').addClass('form-control');
	$('select option:first-child').text('-------');
});
$(function(){
	$('table th').resizable();
});
var formAjaxSubmit = function(form, modal1) {
	$(form).submit(function (e) {
		e.preventDefault();
		$.ajax({
			type: $(this).attr('method'),
			url: $(this).attr('action'),
			data: $(this).serialize(),
			success: function (xhr, ajaxOptions, thrownError) {
				if ( $(xhr).find('.has-error').length > 0 ) {
					$(modal1).find('.modal-body').html(xhr);
					formAjaxSubmit(form, modal1);
				} else {
					$("#myModal2").modal('toggle');
					setTimeout(function(){$('#myModal2').modal('toggle');}, 1000);
					$(modal1).modal('toggle');
				}
			},
			error: function (xhr, ajaxOptions, thrownError) {
			}
		});
	});
}
$("tr").dblclick(function() {
	var url = $(this).find('a').attr('href');
	$('#form-modal-body').load(url, function () {
		$('#form-modal').modal('toggle');
		formAjaxSubmit('#form-modal-body form', '#form-modal');
	});
});
</script>
{% endblock %}

pathogenSite/templates/pathogenSite/pathogen_success.html
{% extends "pathogenSite/base.html" %}

{% block title %}Introduction Page{% endblock %}
{% block content %}
good
{% endblock %}

pathogenSite/templates/pathogenSite/sample_upload_form.html
{% extends 'pathogenSite/base.html' %}
{% block content %}
	<form action="{% url 'sample-upload' %}" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form }}
		<button type="submit" class="btn btn-success">Submit</button>
	</form>

{% endblock %}